### PR TITLE
Upgrade eslint-plugin-react

### PR DESCRIPTION
**Pull request by namjul**

### CODE REVIEW

**Review by reakaleek — APPROVED** [review]

**Review by georggrubner — APPROVED** [review]

**Comment by georggrubner** [comment]
do we want to update others too, or is this not necessary?

**Review by georggrubner — CHANGES_REQUESTED** [review]
why is there no change in package-lock.json?

**Comment by namjul** [comment]
It would be good, but i currently only need this update in design-systems now.

**Review by danielbartsch — APPROVED** [review]

**Comment by namjul** [comment]
Right, i made the change inside the github editor ups

**Review by georggrubner — APPROVED** [review]

**Comment by danielbartsch** [comment]
shouldn't the version be increased, also new tag?

**Comment by georggrubner** [comment]
> shouldn't the version be increased, also new tag?

i think this should be done in the `bump version` commit afterwards

**Comment by namjul** [comment]
Already done with git flow.

**Pull request merged**
