### PR TITLE
Feature/11 remove project configs

### PR DESCRIPTION
**Pull request by namjul**
---

Closes: #11 

---

### How to test
test new eslint-config in:
- insights
- datatap
- components

### CODE REVIEW

**Review by TkDodo — APPROVED** [review]

**Review by danielbartsch — APPROVED** [review]

**Comment by danielbartsch** [comment]
1. how do we proceed with this branch?
  1.a. how to test?
  1.b. just merge it?
2. we should add this prepare commit msg in every repo we use, so the branch name is part of the commit

**Comment by vlabs** [comment]
> we should add this prepare commit msg in every repo we use, so the branch name is part of the commit

:+1:

**Comment by georggrubner** [comment]
how to test?

**Comment by danielbartsch** [comment]
## Test run `#001`

:green_apple: insights
:green_apple: datatap
:green_apple: components

qa approved

**Pull request merged**
