### PR TITLE
Feature/66 no private imports

### LINKED ISSUE #66: no-private-imports
Every feature / component has a "public" interface: It's `index` file. When using a component / a feature, we should _only_ import from that public interface.

However, many features / components have "private" utils / types / hooks. They should be used internally only. If we need them somewhere else, we should move it up. See also: http://handbook.adverity.net/tech-manifest/#utils-types-and-hooks

**Possible implementation**

We could make the directories which this rule should be invoked on customizable to avoid false positives:

```
"no-private-imports": ["error", { "directories": ["features", "components"] } ]
```

This would disallow private imports from `features` or `components`. I think the implementation is rather trivial: Given that we know the importPath, we should error if:

```
directories.some(importPath.startsWith) && importPath.split('/').length > 2
```

Basically, if there is more than one `/` in the path, we are _not_ importing from the public interface:

```
features
  featureA
    index.tsx
    utils.ts
    components
        componentA.tsx
  featureB
```

if `featureB` wants to import from `featureA`:

✅ 
```
import { featureA } from 'features/featureA'
```

❌ 
```
import { fooUtil } from 'features/featureA/utils'
import { fooComponent } from 'features/featureA/components/componentA'
```

So the check for more than one `/` should suffice.

Note that while you are in `featureA`, it is _also_ forbidden to import absolutely from `featureA`:

❌ 
```
import { fooUtil } from 'features/featureA/utils'
```

✅ 
```
import { fooUtil } from './utils'
```

This will also be caught by the rule `no-absolute-internal-imports`

@adamgajzlerowicz what do you think?

### PR DESCRIPTION
**Pull request by adamgajzlerowicz**
Closes https://github.com/pmedianetwork/eslint-config/issues/66

### CODE REVIEW

**Review by woles — APPROVED** [review]

**Review by georggrubner — APPROVED** [review]

**Review by danielbartsch — APPROVED** [review]

**Comment by danielbartsch** [comment]
general question, should there be a jenkins job to run tests?
Now that we have tests in this repo as well

**Comment by adamgajzlerowicz** [comment]
Yes we do - ideally lint + tests. 
Is there an easy way to add this?

**Comment by danielbartsch** [comment]
> Yes we do - ideally lint + tests.
> Is there an easy way to add this?

I think @jglapa or @reakaleek have to add it to the repo via a jenkinsFile. But perhaps we could do that as well, and just copy one from other repos, like here: https://github.com/pmedianetwork/design-system/blob/develop/.jenkins/test.Jenkinsfile

**Comment by adamgajzlerowicz** [comment]
Personally - I'd love to learn how to do this :)

I created a separate issue for it
https://github.com/pmedianetwork/eslint-config/issues/68

**Pull request merged**
