### PR TITLE
chore: bump eslint-config-airbnb to 18.1.0

### LINKED ISSUE #75: Turn off label-has-for rule (deprecated)
The rule is deprecated.
https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/label-has-for.md

### PR DESCRIPTION
**Pull request by dontmakemethink**
---

Closes #75 

---

I have upgraded `eslint-config-airbnb` package to its newest version. It deprecates the rule mentioned in the linked issue.

### CODE REVIEW

**Review by TkDodo — APPROVED** [review]

**Review by adamgajzlerowicz — APPROVED** [review]

**Comment by adamgajzlerowicz** [comment]
Did the tests pass? :smile:

**Comment by dontmakemethink** [comment]
> Did the tests pass? 😄

Sorry, what tests?

**Comment by TkDodo** [comment]
> Did the tests pass? 😄

why are we not running the tests in the PR pipeline ? @reakaleek we need this :)

> Sorry, what tests?

https://github.com/pmedianetwork/eslint-config/tree/develop/tests

**Comment by reakaleek** [comment]
I think tests didn't exist, when the jenkinsfiles were created

**Comment by dontmakemethink** [comment]
image


Can I merge this? :)

**Comment by TkDodo** [comment]
> I think tests didn't exist, when the jenkinsfiles were created

yeah my IDE wasn't showing the `.jenkins` directory. We can easily add the test step to the jenkins file. But we can also do this in another issue, don't mind.

**Comment by reakaleek** [comment]
I think we should put tests in a different jenkinsfile. The current status check's context ist changeset validation, which might get confusing

**Comment by TkDodo** [comment]
@dontmakemethink please resolve the conflicts then we can merge this

**Comment by dontmakemethink** [comment]
@reakaleek @TkDodo 
The pr-checks check is failing:

> Using context: pr-checks
> ERROR: /var/lib/jenkins/jobs/eslint-config/jobs/pull-request/workspace@script/.jenkins/checks.Jenkinsfile not found
> Finished: FAILURE

help pls!

**Comment by reakaleek** [comment]
hmm .. there is something off

**Comment by reakaleek** [comment]
okay.. it's because this pr was not completed:

https://github.com/pmedianetwork/eslint-config/pull/79

**Comment by reakaleek** [comment]
so officially there are no checks yet.. but I don't know why this `checks` is required

**Comment by TkDodo** [comment]
okay, someone needs to pick up #79 and address the comments. @adamgajzlerowicz ❓

**Pull request merged**
